apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomad-ctrl-plane
  labels:
    app: nomad-ctrl-plane
    app.kubernetes.io/name: nomad-ctrl-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nomad-ctrl-plane
      app.kubernetes.io/name: nomad-ctrl-plane
  template:
    metadata:
      labels:
        app: nomad-ctrl-plane
        app.kubernetes.io/name: nomad-ctrl-plane
    spec:
      containers:
        - name: nomad-ctrl-plane
          image: ghcr.io/iuliansafta/control-plane:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50051
          args: ["--nomad=$(NOMAD_ADDR)"]
          env:
            - name: NOMAD_ADDR
              valueFrom:
                configMapKeyRef:
                  name: nomad-ctrl-plane-config
                  key: SERVER_ADDR
          # readinessProbe:
          #   failureThreshold: 2
          #   grpc:
          #     port: 50051
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
